--[[
    Demon Slayer RP - Souffles (Respirations) des Pourfendeurs
    ------------------------------------------------------------------
    Ajouter un souffle = ajouter une entrée ici, sans toucher au code.

    Chaque technique hérite de Config.Abilities.TechniqueDefaults et peut surcharger :
      Name, Form, Description, Shape ("cone"|"circle"|"line"|"dash"|"self"),
      Range, Angle, Width, Damage, Cost, CooldownMs, Knockback, Dash, MaxTargets,
      BonusVsDemons (multiplicateur contre les démons), BlockRegenMs (bloque la
      régénération du démon touché), Slow = { Multiplier, DurationMs },
      Buff = { SpeedMultiplier, DamageMultiplier, Heal, DurationMs } (sur soi),
      Animation, AnimationSlot, Effect, EffectDuration, EffectOffset, Sound.

    Techniques : les 4 premières vont sur les touches 1 à 4, la 5e est la
    technique spéciale (touche X par défaut).
]]

local CHOP = "nanos-world::A_Mannequin_Taunt_Chop"
local KUNFU = "nanos-world::A_Mannequin_Taunt_Kunfu"
local PUNCH = "nanos-world::A_Mannequin_Taunt_HandPunch"
local THROW = "nanos-world::A_Mannequin_Throw_01"
local THROW2 = "nanos-world::A_Mannequin_Throw_02"

Config.BreathingStyles = {

    eau = {
        Name = "Souffle de l'Eau",
        Description = "Style fluide et adaptable, enseigne par Sakonji Urokodaki.",
        Color = "cyan",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Tranchant de la surface de l'eau", Description = "Coup horizontal net.",
              Damage = 22, Cost = 12, CooldownMs = 2500, Range = 350, Angle = 70,
              Effect = "nanos-world::P_FXVariety_WaterBallHit", Sound = "nanos-world::A_Water_Impact_MS" },
            { Form = 2, Name = "Roue a eau", Description = "Rotation verticale autour de soi.",
              Shape = "circle", Range = 300, Damage = 20, Cost = 15, CooldownMs = 4000, Knockback = 400,
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_Explosion_Water", EffectOffset = 0 },
            { Form = 4, Name = "Maree frappante", Description = "Enchainement de coups en avancant.",
              Shape = "dash", Range = 600, Width = 220, Dash = 1200, Damage = 26, Cost = 20, CooldownMs = 5000,
              Effect = "nanos-world::P_FXVariety_WaterBall" },
            { Form = 8, Name = "Bassin de la cascade", Description = "Frappe verticale puissante.",
              Range = 300, Angle = 50, Damage = 34, Cost = 25, CooldownMs = 7000, Knockback = 600,
              Animation = PUNCH, Effect = "nanos-world::P_FXVariety_AquaStorm", EffectDuration = 2 },
            { Form = 10, Name = "Dragon changeant", Description = "Technique ultime : chaque coup gagne en force.",
              Shape = "dash", Range = 900, Width = 300, Dash = 1600, Damage = 50, Cost = 45, CooldownMs = 20000,
              Knockback = 700, AnimationSlot = "FullBody", Effect = "nanos-world::P_FXVariety_AquaStorm", EffectDuration = 3 },
        },
    },

    flamme = {
        Name = "Souffle de la Flamme",
        Description = "Style offensif et direct de la famille Rengoku.",
        Color = "orange",
        BlockRegenMs = 2500,
        Techniques = {
            { Form = 1, Name = "Feu inconnu", Description = "Charge fulgurante enflammee.",
              Shape = "dash", Range = 700, Dash = 1500, Damage = 25, Cost = 15, CooldownMs = 3500,
              Effect = "nanos-world::P_FXVariety_FireBall", Sound = "nanos-world::A_Explosion_Small" },
            { Form = 2, Name = "Ciel ascendant", Description = "Coup ascendant en arc de flammes.",
              Range = 350, Angle = 80, Damage = 22, Cost = 14, CooldownMs = 3000, Knockback = 500,
              Animation = PUNCH, Effect = "nanos-world::P_Fire_Exp_01" },
            { Form = 4, Name = "Ondulation de la flamme en fleur", Description = "Rideau de flammes protecteur.",
              Shape = "circle", Range = 320, Damage = 18, Cost = 18, CooldownMs = 6000, Knockback = 450,
              Buff = { DamageMultiplier = 1.2, DurationMs = 5000 },
              AnimationSlot = "FullBody", Animation = KUNFU, Effect = "nanos-world::P_Fire_Grd_01", EffectOffset = 0, EffectDuration = 2.5 },
            { Form = 5, Name = "Tigre flamboyant", Description = "Frappe devastatrice en forme de tigre.",
              Range = 450, Angle = 100, Damage = 35, Cost = 28, CooldownMs = 8000, Knockback = 650,
              Effect = "nanos-world::P_FXVariety_FireStorm", EffectDuration = 2, Sound = "nanos-world::A_Explosion_Large" },
            { Form = 9, Name = "Purgatoire", Description = "Technique ultime de Kyojuro Rengoku.",
              Shape = "dash", Range = 1000, Width = 320, Dash = 1800, Damage = 55, Cost = 50, CooldownMs = 22000,
              Knockback = 900, AnimationSlot = "FullBody", Effect = "nanos-world::P_Explosion_Fire_03",
              EffectDuration = 3, Sound = "nanos-world::A_Explosion_Large" },
        },
    },

    tonnerre = {
        Name = "Souffle du Tonnerre",
        Description = "Vitesse extreme concentree dans les jambes.",
        Color = "yellow",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Eclair foudroyant", Description = "Degainer eclair a pleine vitesse.",
              Shape = "dash", Range = 900, Width = 200, Dash = 2200, Damage = 30, Cost = 18, CooldownMs = 4000,
              Effect = "nanos-world::P_FXVariety_Lightning_01" },
            { Form = 2, Name = "Esprit du riz", Description = "Cinq coups en arc autour de soi.",
              Shape = "circle", Range = 280, Damage = 20, Cost = 15, CooldownMs = 4000,
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_FXVariety_ThunderBallHit", EffectOffset = 0 },
            { Form = 3, Name = "Essaim de tonnerre", Description = "Rafale de coups vers l'avant.",
              Range = 400, Angle = 110, Damage = 24, Cost = 18, CooldownMs = 5000,
              Effect = "nanos-world::P_FXVariety_Lightning_02" },
            { Form = 4, Name = "Tonnerre lointain", Description = "Coup porte a longue distance.",
              Shape = "line", Range = 1000, Width = 160, Damage = 22, Cost = 16, CooldownMs = 5000,
              Animation = THROW, Effect = "nanos-world::P_FXVariety_Lightning_03" },
            { Form = 7, Name = "Honoikazuchi no Kami", Description = "Septieme forme creee par Zenitsu : un dragon de foudre.",
              Shape = "dash", Range = 1300, Width = 280, Dash = 2800, Damage = 55, Cost = 50, CooldownMs = 22000,
              Knockback = 600, AnimationSlot = "FullBody", Effect = "nanos-world::P_FXVariety_ThunderStorm", EffectDuration = 3 },
        },
    },

    vent = {
        Name = "Souffle du Vent",
        Description = "Tranchants violents comme des bourrasques.",
        Color = "green",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Tourbillon tranchant", Description = "Charge en spirale.",
              Shape = "dash", Range = 700, Dash = 1500, Damage = 24, Cost = 15, CooldownMs = 3500,
              Effect = "nanos-world::P_FXVariety_Storm" },
            { Form = 2, Name = "Griffes purificatrices", Description = "Quatre entailles de vent.",
              Range = 380, Angle = 90, Damage = 24, Cost = 15, CooldownMs = 3000,
              Effect = "nanos-world::P_ShockWave_03" },
            { Form = 3, Name = "Arbre de la tempete", Description = "Tornade defensive autour de soi.",
              Shape = "circle", Range = 350, Damage = 20, Cost = 18, CooldownMs = 5000, Knockback = 700,
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_FXVariety_Storm", EffectOffset = 0, EffectDuration = 2 },
            { Form = 5, Name = "Vent froid de montagne", Description = "Lame de vent projetee au loin.",
              Shape = "line", Range = 1100, Width = 180, Damage = 22, Cost = 16, CooldownMs = 5000,
              Animation = THROW, Effect = "nanos-world::P_ShockWave_07" },
            { Form = 9, Name = "Typhon Idaten", Description = "Technique ultime de Sanemi Shinazugawa.",
              Shape = "circle", Range = 550, Damage = 48, Cost = 48, CooldownMs = 21000, Knockback = 1000,
              AnimationSlot = "FullBody", Animation = KUNFU, Effect = "nanos-world::P_FXVariety_DarkStorm", EffectOffset = 0, EffectDuration = 3 },
        },
    },

    pierre = {
        Name = "Souffle de la Pierre",
        Description = "Le plus puissant des souffles, lent mais ecrasant.",
        Color = "grey",
        BlockRegenMs = 3000,
        Techniques = {
            { Form = 1, Name = "Serpentinite bipolaire", Description = "Lancer de la hache et du fleau.",
              Shape = "line", Range = 900, Width = 200, Damage = 30, Cost = 18, CooldownMs = 5000, Knockback = 500,
              Animation = THROW2, Effect = "nanos-world::P_HighImpact", Sound = "nanos-world::A_BigHammer_Impact" },
            { Form = 2, Name = "Frappe ascendante", Description = "Coup ecrasant vers le haut.",
              Range = 300, Angle = 70, Damage = 34, Cost = 20, CooldownMs = 5000, Knockback = 700,
              Animation = PUNCH, Effect = "nanos-world::P_ImpactExplosion_02", Sound = "nanos-world::A_BigHammer_Impact" },
            { Form = 3, Name = "Peau de pierre", Description = "Endurcit le corps.",
              Shape = "self", Cost = 20, CooldownMs = 15000, Damage = 0,
              Buff = { DamageMultiplier = 1.3, Heal = 15, DurationMs = 8000 },
              Animation = "nanos-world::A_Mannequin_Taunt_Flex_01", Effect = "nanos-world::P_FXVariety_MagicCircle", EffectOffset = 0, EffectDuration = 2 },
            { Form = 4, Name = "Conquete du roc volcanique", Description = "Pluie de coups autour de soi.",
              Shape = "circle", Range = 400, Damage = 32, Cost = 26, CooldownMs = 8000, Knockback = 600,
              AnimationSlot = "FullBody", Animation = KUNFU, Effect = "nanos-world::P_Destruction", EffectOffset = 0, EffectDuration = 2 },
            { Form = 5, Name = "Arcs de justice", Description = "Technique ultime de Gyomei Himejima.",
              Shape = "circle", Range = 600, Damage = 60, Cost = 55, CooldownMs = 25000, Knockback = 1100,
              AnimationSlot = "FullBody", Animation = PUNCH, Effect = "nanos-world::P_ImpactExplosion_06", EffectOffset = 0,
              EffectDuration = 3, Sound = "nanos-world::A_Explosion_Large" },
        },
    },

    brume = {
        Name = "Souffle de la Brume",
        Description = "Derive du vent : mouvements trompeurs et insaisissables.",
        Color = "grey",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Nuages bas, brume lointaine", Description = "Estoc rapide.",
              Shape = "line", Range = 500, Width = 140, Damage = 24, Cost = 13, CooldownMs = 2500,
              Effect = "nanos-world::P_Smoke_02" },
            { Form = 2, Name = "Brume aux huit couches", Description = "Huit coups enchaines.",
              Range = 380, Angle = 100, Damage = 26, Cost = 18, CooldownMs = 4500,
              Effect = "nanos-world::P_Smoke_04" },
            { Form = 4, Name = "Tranchant du flux changeant", Description = "Coup glissant au ras du sol.",
              Shape = "dash", Range = 600, Dash = 1300, Damage = 24, Cost = 16, CooldownMs = 4000,
              Effect = "nanos-world::P_Distortion_01" },
            { Form = 5, Name = "Mer de nuages", Description = "Nuage aveuglant qui ralentit les ennemis.",
              Shape = "circle", Range = 450, Damage = 12, Cost = 20, CooldownMs = 9000,
              Slow = { Multiplier = 0.5, DurationMs = 3000 },
              AnimationSlot = "FullBody", Animation = KUNFU, Effect = "nanos-world::P_Smoke_06", EffectOffset = 0, EffectDuration = 3 },
            { Form = 7, Name = "Brume obscurcissante", Description = "Forme creee par Muichiro Tokito.",
              Shape = "dash", Range = 900, Width = 280, Dash = 1500, Damage = 50, Cost = 45, CooldownMs = 20000,
              Buff = { SpeedMultiplier = 1.4, DurationMs = 5000 },
              AnimationSlot = "FullBody", Effect = "nanos-world::P_Smoke_07", EffectDuration = 3 },
        },
    },

    amour = {
        Name = "Souffle de l'Amour",
        Description = "Derive de la flamme, lame souple comme un fouet.",
        Color = "purple",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Frissons du premier amour", Description = "Charge avec une rafale de coups.",
              Shape = "dash", Range = 650, Dash = 1400, Damage = 22, Cost = 14, CooldownMs = 3500,
              Effect = "nanos-world::P_FlareShimmer_01" },
            { Form = 2, Name = "Peines d'amour", Description = "Coups larges en eventail.",
              Range = 420, Angle = 140, Damage = 22, Cost = 15, CooldownMs = 3500,
              Effect = "nanos-world::P_Burst_01" },
            { Form = 3, Name = "Averse feline", Description = "Lame souple qui fouette autour.",
              Shape = "circle", Range = 380, Damage = 20, Cost = 16, CooldownMs = 4500,
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_SparksFlair", EffectOffset = 0 },
            { Form = 5, Name = "Griffes sauvages de l'amour", Description = "Fouet longue portee.",
              Shape = "line", Range = 800, Width = 200, Damage = 26, Cost = 18, CooldownMs = 5000,
              Animation = THROW, Effect = "nanos-world::P_Ribbon" },
            { Form = 6, Name = "Vents de l'amour", Description = "Technique ultime de Mitsuri Kanroji.",
              Shape = "circle", Range = 550, Damage = 46, Cost = 45, CooldownMs = 20000, Knockback = 700,
              AnimationSlot = "FullBody", Animation = KUNFU, Effect = "nanos-world::P_OmnidirectionalBurst", EffectOffset = 0, EffectDuration = 2.5 },
        },
    },

    serpent = {
        Name = "Souffle du Serpent",
        Description = "Derive de l'eau, trajectoires sinueuses imprevisibles.",
        Color = "purple",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Tranchant sinueux", Description = "Coup ondulant.",
              Range = 380, Angle = 80, Damage = 22, Cost = 12, CooldownMs = 2500,
              Effect = "nanos-world::P_Streamer" },
            { Form = 2, Name = "Crochets venimeux", Description = "Estoc precis a distance.",
              Shape = "line", Range = 650, Width = 130, Damage = 28, Cost = 16, CooldownMs = 4000,
              Effect = "nanos-world::P_DirectionalBurst" },
            { Form = 3, Name = "Etreinte enroulee", Description = "Encercle et ralentit la cible.",
              Shape = "circle", Range = 320, Damage = 18, Cost = 16, CooldownMs = 6000,
              Slow = { Multiplier = 0.6, DurationMs = 2500 },
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_Ribbon", EffectOffset = 0 },
            { Form = 4, Name = "Reptile a deux tetes", Description = "Deux coups simultanes.",
              Range = 400, Angle = 120, Damage = 26, Cost = 18, CooldownMs = 5000,
              Effect = "nanos-world::P_Streamer" },
            { Form = 5, Name = "Serpent ondoyant", Description = "Technique ultime d'Obanai Iguro.",
              Shape = "dash", Range = 1000, Width = 260, Dash = 1700, Damage = 50, Cost = 45, CooldownMs = 20000,
              AnimationSlot = "FullBody", Effect = "nanos-world::P_FXVariety_DarkStorm", EffectDuration = 2.5 },
        },
    },

    insecte = {
        Name = "Souffle de l'Insecte",
        Description = "Peu de force mais un poison mortel pour les demons.",
        Color = "purple",
        BlockRegenMs = 6000,
        BonusVsDemons = 1.4,
        Techniques = {
            { Form = 1, Name = "Danse du papillon : Caprice", Description = "Estoc empoisonne.",
              Shape = "line", Range = 550, Width = 120, Damage = 14, Cost = 12, CooldownMs = 2500,
              Effect = "nanos-world::P_FlareShimmer_02" },
            { Form = 2, Name = "Dard d'abeille", Description = "Piqure fulgurante.",
              Shape = "dash", Range = 600, Width = 150, Dash = 1500, Damage = 16, Cost = 14, CooldownMs = 3500,
              Effect = "nanos-world::P_Sparks" },
            { Form = 3, Name = "Hexagone de la libellule", Description = "Six piqures en un instant.",
              Range = 350, Angle = 60, Damage = 20, Cost = 16, CooldownMs = 4000, BlockRegenMs = 9000,
              Effect = "nanos-world::P_SparksFlair" },
            { Form = 5, Name = "Zigzag du mille-pattes", Description = "Deplacement en zigzag puis frappe.",
              Shape = "dash", Range = 800, Width = 250, Dash = 1800, Damage = 20, Cost = 18, CooldownMs = 5000,
              Slow = { Multiplier = 0.6, DurationMs = 3000 }, Effect = "nanos-world::P_FlareShimmer_01" },
            { Form = 6, Name = "Poison de glycine", Description = "Dose massive : bloque longuement la regeneration.",
              Shape = "line", Range = 600, Width = 150, Damage = 30, Cost = 40, CooldownMs = 20000,
              BlockRegenMs = 20000, Slow = { Multiplier = 0.5, DurationMs = 5000 },
              Effect = "nanos-world::P_FXVariety_HealAura", EffectDuration = 2.5 },
        },
    },

    fleur = {
        Name = "Souffle de la Fleur",
        Description = "Derive de l'eau, elegant et precis.",
        Color = "rose",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 2, Name = "Prunier honorable", Description = "Quatre coups en croix.",
              Range = 360, Angle = 80, Damage = 22, Cost = 13, CooldownMs = 2800,
              Effect = "nanos-world::P_Burst_02" },
            { Form = 4, Name = "Hanagoromo cramoisi", Description = "Coup en arc ample.",
              Range = 420, Angle = 130, Damage = 22, Cost = 15, CooldownMs = 3500,
              Effect = "nanos-world::P_Burst_01" },
            { Form = 5, Name = "Pivoines de la futilite", Description = "Neuf coups autour de soi.",
              Shape = "circle", Range = 340, Damage = 24, Cost = 18, CooldownMs = 5000,
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_OmnidirectionalBurst", EffectOffset = 0 },
            { Form = 6, Name = "Pecher tourbillonnant", Description = "Tourbillon defensif.",
              Shape = "circle", Range = 300, Damage = 16, Cost = 15, CooldownMs = 5000, Knockback = 600,
              Effect = "nanos-world::P_Burst_02", EffectOffset = 0 },
            { Form = 7, Name = "Oeil vermillon de l'equinoxe", Description = "Vision acceleree au prix d'un grand effort.",
              Shape = "self", Damage = 0, Cost = 40, CooldownMs = 25000,
              Buff = { SpeedMultiplier = 1.5, DamageMultiplier = 1.4, DurationMs = 8000 },
              Animation = "nanos-world::A_Mannequin_Taunt_EyesOnYou", Effect = "nanos-world::P_FXVariety_HealAura", EffectOffset = 0, EffectDuration = 2 },
        },
    },

    son = {
        Name = "Souffle du Son",
        Description = "Derive du tonnerre : explosions rythmees.",
        Color = "yellow",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Rugissement", Description = "Frappe explosive au sol.",
              Range = 350, Angle = 90, Damage = 26, Cost = 16, CooldownMs = 3500, Knockback = 500,
              Animation = PUNCH, Effect = "nanos-world::P_Explosive_02", Sound = "nanos-world::A_Explosion_Small" },
            { Form = 2, Name = "Echo explosif", Description = "Detonation autour de soi.",
              Shape = "circle", Range = 330, Damage = 22, Cost = 16, CooldownMs = 4500, Knockback = 600,
              Effect = "nanos-world::P_Explosive_05", EffectOffset = 0, Sound = "nanos-world::A_Explosion_Small" },
            { Form = 4, Name = "Tranchants resonnants", Description = "Rotation rapide des deux lames.",
              Shape = "dash", Range = 600, Dash = 1300, Damage = 24, Cost = 18, CooldownMs = 4500,
              Effect = "nanos-world::P_ShockWave_05" },
            { Form = 5, Name = "Representation des cordes", Description = "Salve d'explosions a distance.",
              Shape = "line", Range = 900, Width = 220, Damage = 26, Cost = 20, CooldownMs = 6000,
              Animation = THROW, Effect = "nanos-world::P_Explosive_07", Sound = "nanos-world::A_Explosion_Small" },
            { Form = 0, Name = "Partition complete", Description = "Technique ultime de Tengen Uzui.",
              Shape = "circle", Range = 550, Damage = 48, Cost = 48, CooldownMs = 21000, Knockback = 900,
              AnimationSlot = "FullBody", Animation = KUNFU, Effect = "nanos-world::P_FXVariety_Explosion", EffectOffset = 0,
              EffectDuration = 3, Sound = "nanos-world::A_Explosion_Large" },
        },
    },

    bete = {
        Name = "Souffle de la Bete",
        Description = "Style sauvage invente par Inosuke Hashibira, deux lames dentelees.",
        Color = "grey",
        BlockRegenMs = 2000,
        Techniques = {
            { Form = 1, Name = "Percer", Description = "Double estoc en avancant.",
              Shape = "dash", Range = 650, Dash = 1500, Damage = 24, Cost = 14, CooldownMs = 3500,
              Effect = "nanos-world::P_FXVariety_Hit_02" },
            { Form = 2, Name = "Dechirer", Description = "Deux coups en ciseaux.",
              Range = 340, Angle = 90, Damage = 24, Cost = 14, CooldownMs = 3000,
              Effect = "nanos-world::P_FXVariety_Hit_01" },
            { Form = 3, Name = "Devorer", Description = "Coup en machoire sur une cible.",
              Range = 280, Angle = 50, Damage = 32, Cost = 18, CooldownMs = 5000,
              Animation = PUNCH, Effect = "nanos-world::P_HighImpact" },
            { Form = 5, Name = "Decoupe insensee", Description = "Coups desordonnes tout autour.",
              Shape = "circle", Range = 330, Damage = 24, Cost = 18, CooldownMs = 5000,
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_FXVariety_Hit_02", EffectOffset = 0 },
            { Form = 7, Name = "Lancer brutal", Description = "Lance une lame a toute force.",
              Shape = "line", Range = 1100, Width = 160, Damage = 45, Cost = 40, CooldownMs = 18000, Knockback = 500,
              Animation = THROW2, Effect = "nanos-world::P_FXVariety_ShotShockWave", EffectDuration = 2 },
        },
    },

    soleil = {
        Name = "Souffle du Soleil (Hinokami Kagura)",
        Description = "Le premier des souffles. Redoutable contre les demons.",
        Color = "red",
        BlockRegenMs = 8000,
        BonusVsDemons = 1.5,
        Techniques = {
            { Form = 1, Name = "Danse", Description = "Coup descendant en cercle de feu.",
              Range = 380, Angle = 90, Damage = 28, Cost = 18, CooldownMs = 3500,
              Effect = "nanos-world::P_Fire_Exp_02", Sound = "nanos-world::A_Explosion_Small" },
            { Form = 2, Name = "Ciel bleu clair", Description = "Rotation complete enflammee.",
              Shape = "circle", Range = 340, Damage = 26, Cost = 20, CooldownMs = 5000,
              Animation = KUNFU, AnimationSlot = "FullBody", Effect = "nanos-world::P_FXVariety_FireStorm", EffectOffset = 0 },
            { Form = 3, Name = "Soleil ardent", Description = "Saut et coup vertical.",
              Shape = "dash", Range = 700, Dash = 1500, Damage = 30, Cost = 22, CooldownMs = 5500,
              Effect = "nanos-world::P_Explosion_Fire_02" },
            { Form = 4, Name = "Tournesol perforant", Description = "Estoc fulgurant.",
              Shape = "line", Range = 800, Width = 150, Damage = 32, Cost = 24, CooldownMs = 6000,
              Effect = "nanos-world::P_FXVariety_ShootingStar" },
            { Form = 13, Name = "Treizieme forme", Description = "Enchainement des douze formes, sans fin.",
              Shape = "circle", Range = 650, Damage = 62, Cost = 60, CooldownMs = 28000, Knockback = 900,
              AnimationSlot = "FullBody", Animation = KUNFU, Effect = "nanos-world::P_Explosion_Fire_06", EffectOffset = 0,
              EffectDuration = 3, Sound = "nanos-world::A_Explosion_Large" },
        },
    },
}
