--[[
    Demon Slayer RP - Catalogue du pack Niagara "demonslayer-vfx" (GÉNÉRÉ, ne pas modifier à la main)
    ------------------------------------------------------------------
    Source : DemonSlayerVFX/Tools/vfx_catalog.py
    Rôle d'effet du gamemode -> Niagara System du pack, par élément.
    Utilisé par Client/Systems/VFX/Core/VFXPack.lua quand Config.Vfx.Pack.Enabled = true.
]]

Config.VfxPackCatalog = {
    PackId = "demonslayer-vfx",
    Systems = {
        "NS_Core_Trail",
        "NS_Core_RibbonTrail",
        "NS_Core_EnergyTrail",
        "NS_Core_ElementTrail",
        "NS_Core_Flash",
        "NS_Core_Shockwave",
        "NS_Core_Distortion",
        "NS_Core_SpeedLines",
        "NS_Core_Sparks",
        "NS_Core_Debris",
        "NS_Impact_Small",
        "NS_Impact_Medium",
        "NS_Impact_Large",
        "NS_Impact_Massive",
        "NS_VFX_Water_Slash",
        "NS_VFX_Water_Trail",
        "NS_VFX_Water_Wave",
        "NS_VFX_Water_Tsunami",
        "NS_VFX_Water_Tornado",
        "NS_VFX_Water_Ball",
        "NS_VFX_Water_Dragon",
        "NS_VFX_Water_Explosion",
        "NS_VFX_Water_Impact",
        "NS_VFX_Water_Dash",
        "NS_VFX_Fire_Slash",
        "NS_VFX_Fire_Trail",
        "NS_VFX_Fire_Burst",
        "NS_VFX_Fire_Explosion",
        "NS_VFX_Fire_Dragon",
        "NS_VFX_Fire_Impact",
        "NS_VFX_Thunder_Dash",
        "NS_VFX_Thunder_Slash",
        "NS_VFX_Thunder_Burst",
        "NS_VFX_Thunder_Impact",
        "NS_VFX_Thunder_Explosion",
        "NS_VFX_Wind_Slash",
        "NS_VFX_Wind_Trail",
        "NS_VFX_Wind_Tornado",
        "NS_VFX_Wind_Blade",
        "NS_VFX_Wind_Impact",
        "NS_VFX_Wind_Dash",
        "NS_VFX_Mist_Slash",
        "NS_VFX_Mist_Trail",
        "NS_VFX_Mist_Fog",
        "NS_VFX_Mist_Vanish",
        "NS_VFX_Mist_Impact",
        "NS_VFX_Blood_Slash",
        "NS_VFX_Blood_Burst",
        "NS_VFX_Blood_Projectile",
        "NS_VFX_Blood_Aura",
        "NS_VFX_Blood_Impact",
        "NS_VFX_Ice_Slash",
        "NS_VFX_Ice_Spikes",
        "NS_VFX_Ice_Shard",
        "NS_VFX_Ice_Explosion",
        "NS_VFX_Ice_Impact",
        "NS_VFX_Shadow_Slash",
        "NS_VFX_Shadow_Vortex",
        "NS_VFX_Shadow_Projectile",
        "NS_VFX_Shadow_Aura",
        "NS_VFX_Shadow_Impact",
        "NS_VFX_Flower_Slash",
        "NS_VFX_Flower_PetalStorm",
        "NS_VFX_Flower_Bloom",
        "NS_VFX_Flower_Projectile",
        "NS_VFX_Flower_Impact",
    },
    Roles = {
        beast = { Burst = "NS_Impact_Large", Dash = "NS_VFX_Wind_Dash", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Wind_Impact", Projectile = "NS_VFX_Wind_Blade", Slash = "NS_VFX_Wind_Slash", Tornado = "NS_VFX_Wind_Tornado", Trail = "NS_VFX_Wind_Trail", Zone = "NS_VFX_Wind_Tornado" },
        blood = { Burst = "NS_VFX_Blood_Burst", Dash = "NS_Core_SpeedLines", Explosion = "NS_VFX_Blood_Burst", Impact = "NS_VFX_Blood_Impact", Projectile = "NS_VFX_Blood_Projectile", Slash = "NS_VFX_Blood_Slash", Trail = "NS_Core_ElementTrail", Zone = "NS_VFX_Blood_Aura" },
        flame = { Burst = "NS_VFX_Fire_Burst", Dash = "NS_Core_SpeedLines", Dragon = "NS_VFX_Fire_Dragon", Explosion = "NS_VFX_Fire_Explosion", Impact = "NS_VFX_Fire_Impact", Slash = "NS_VFX_Fire_Slash", Trail = "NS_VFX_Fire_Trail" },
        flower = { Burst = "NS_VFX_Flower_Bloom", Dash = "NS_Core_SpeedLines", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Flower_Impact", Projectile = "NS_VFX_Flower_Projectile", Slash = "NS_VFX_Flower_Slash", Trail = "NS_Core_ElementTrail", Zone = "NS_VFX_Flower_PetalStorm" },
        ice = { Burst = "NS_VFX_Ice_Explosion", Dash = "NS_Core_SpeedLines", Explosion = "NS_VFX_Ice_Explosion", Impact = "NS_VFX_Ice_Impact", Projectile = "NS_VFX_Ice_Shard", Slash = "NS_VFX_Ice_Slash", Spikes = "NS_VFX_Ice_Spikes", Trail = "NS_Core_ElementTrail" },
        insect = { Burst = "NS_VFX_Flower_Bloom", Dash = "NS_Core_SpeedLines", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Flower_Impact", Projectile = "NS_VFX_Flower_Projectile", Slash = "NS_VFX_Flower_Slash", Trail = "NS_Core_ElementTrail", Zone = "NS_VFX_Flower_PetalStorm" },
        love = { Burst = "NS_VFX_Flower_Bloom", Dash = "NS_Core_SpeedLines", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Flower_Impact", Projectile = "NS_VFX_Flower_Projectile", Slash = "NS_VFX_Flower_Slash", Trail = "NS_Core_ElementTrail", Zone = "NS_VFX_Flower_PetalStorm" },
        mist = { Burst = "NS_Impact_Large", Dash = "NS_VFX_Mist_Vanish", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Mist_Impact", Slash = "NS_VFX_Mist_Slash", Trail = "NS_VFX_Mist_Trail", Zone = "NS_VFX_Mist_Fog" },
        neutral = { Burst = "NS_Impact_Large", Dash = "NS_Core_SpeedLines", Explosion = "NS_Impact_Massive", Impact = "NS_Impact_Medium", Slash = "NS_Core_EnergyTrail", Trail = "NS_Core_ElementTrail" },
        serpent = { Burst = "NS_Impact_Large", Dash = "NS_Core_SpeedLines", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Shadow_Impact", Projectile = "NS_VFX_Shadow_Projectile", Slash = "NS_VFX_Shadow_Slash", Tornado = "NS_VFX_Shadow_Vortex", Trail = "NS_Core_ElementTrail", Zone = "NS_VFX_Shadow_Vortex" },
        shadow = { Burst = "NS_Impact_Large", Dash = "NS_Core_SpeedLines", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Shadow_Impact", Projectile = "NS_VFX_Shadow_Projectile", Slash = "NS_VFX_Shadow_Slash", Tornado = "NS_VFX_Shadow_Vortex", Trail = "NS_Core_ElementTrail", Zone = "NS_VFX_Shadow_Vortex" },
        sound = { Burst = "NS_VFX_Thunder_Burst", Dash = "NS_VFX_Thunder_Dash", Explosion = "NS_VFX_Thunder_Explosion", Impact = "NS_VFX_Thunder_Impact", Slash = "NS_VFX_Thunder_Slash", Trail = "NS_Core_ElementTrail" },
        stone = { Burst = "NS_Impact_Large", Dash = "NS_Core_SpeedLines", Explosion = "NS_Impact_Massive", Impact = "NS_Impact_Medium", Slash = "NS_Core_EnergyTrail", Trail = "NS_Core_ElementTrail" },
        sun = { Burst = "NS_VFX_Fire_Burst", Dash = "NS_Core_SpeedLines", Dragon = "NS_VFX_Fire_Dragon", Explosion = "NS_VFX_Fire_Explosion", Impact = "NS_VFX_Fire_Impact", Slash = "NS_VFX_Fire_Slash", Trail = "NS_VFX_Fire_Trail" },
        thunder = { Burst = "NS_VFX_Thunder_Burst", Dash = "NS_VFX_Thunder_Dash", Explosion = "NS_VFX_Thunder_Explosion", Impact = "NS_VFX_Thunder_Impact", Slash = "NS_VFX_Thunder_Slash", Trail = "NS_Core_ElementTrail" },
        water = { Burst = "NS_VFX_Water_Explosion", Dash = "NS_VFX_Water_Dash", Dragon = "NS_VFX_Water_Dragon", Explosion = "NS_VFX_Water_Explosion", Impact = "NS_VFX_Water_Impact", Projectile = "NS_VFX_Water_Ball", Slash = "NS_VFX_Water_Slash", Tornado = "NS_VFX_Water_Tornado", Trail = "NS_VFX_Water_Trail", Tsunami = "NS_VFX_Water_Tsunami", Wave = "NS_VFX_Water_Wave", Zone = "NS_VFX_Water_Tornado" },
        wind = { Burst = "NS_Impact_Large", Dash = "NS_VFX_Wind_Dash", Explosion = "NS_Impact_Massive", Impact = "NS_VFX_Wind_Impact", Projectile = "NS_VFX_Wind_Blade", Slash = "NS_VFX_Wind_Slash", Tornado = "NS_VFX_Wind_Tornado", Trail = "NS_VFX_Wind_Trail", Zone = "NS_VFX_Wind_Tornado" },
    },
    Impacts = { Small = "NS_Impact_Small", Medium = "NS_Impact_Medium", Large = "NS_Impact_Large", Massive = "NS_Impact_Massive" },
}
